# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/lib/ui/add_associate.ui'
#
# Created: Mon Feb 10 18:26:45 2014
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dock(object):
    def setupUi(self, Dock):
        Dock.setObjectName("Dock")
        Dock.setWindowModality(QtCore.Qt.WindowModal)
        Dock.resize(770, 877)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dock.sizePolicy().hasHeightForWidth())
        Dock.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/associate_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dock.setWindowIcon(icon)
        Dock.setStyleSheet("QDockWidget::title\n"
"{\n"
"   font-family: \"Roboto Lt\";\n"
"   font-size: 18pt;\n"
"   background: lightgray;\n"
"   padding-left: 10px; \n"
"   padding-top: 4px;\n"
"}")
        Dock.setFloating(False)
        Dock.setFeatures(QtGui.QDockWidget.DockWidgetClosable)
        Dock.setAllowedAreas(QtCore.Qt.TopDockWidgetArea)
        self.Contents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Contents.sizePolicy().hasHeightForWidth())
        self.Contents.setSizePolicy(sizePolicy)
        self.Contents.setObjectName("Contents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.Contents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 726, 734))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(703, 247))
        self.groupBox.setMaximumSize(QtCore.QSize(703, 231))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(" QGroupBox {\n"
"     font-weight: bold;\n"
"     border: 2px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 25px;\n"
" }\n"
"\n"
" QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top left;\n"
" }")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 2, 1, 1)
        self.edNickname = QtGui.QLineEdit(self.groupBox)
        self.edNickname.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.edNickname.setInputMask("")
        self.edNickname.setObjectName("edNickname")
        self.gridLayout.addWidget(self.edNickname, 1, 1, 1, 4)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.edCPF = QtGui.QLineEdit(self.groupBox)
        self.edCPF.setObjectName("edCPF")
        self.gridLayout.addWidget(self.edCPF, 2, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.edFullName = QtGui.QLineEdit(self.groupBox)
        self.edFullName.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.edFullName.setObjectName("edFullName")
        self.gridLayout.addWidget(self.edFullName, 0, 1, 1, 4)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.edEmail = QtGui.QLineEdit(self.groupBox)
        self.edEmail.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.edEmail.setObjectName("edEmail")
        self.gridLayout.addWidget(self.edEmail, 5, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.edRG = QtGui.QLineEdit(self.groupBox)
        self.edRG.setInputMask("")
        self.edRG.setObjectName("edRG")
        self.gridLayout.addWidget(self.edRG, 2, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 3, 1, 1)
        self.edProfession = QtGui.QLineEdit(self.groupBox)
        self.edProfession.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edProfession.setObjectName("edProfession")
        self.gridLayout.addWidget(self.edProfession, 3, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(681, 235))
        self.groupBox_2.setMaximumSize(QtCore.QSize(681, 231))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet(" QGroupBox {\n"
"     font-weight: bold;\n"
"     border: 2px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 25px;\n"
" }\n"
"\n"
" QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top left;\n"
" }")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.edStreet = QtGui.QLineEdit(self.groupBox_2)
        self.edStreet.setObjectName("edStreet")
        self.gridLayout_2.addWidget(self.edStreet, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.edComplement = QtGui.QLineEdit(self.groupBox_2)
        self.edComplement.setObjectName("edComplement")
        self.gridLayout_2.addWidget(self.edComplement, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.edDistrict = QtGui.QLineEdit(self.groupBox_2)
        self.edDistrict.setObjectName("edDistrict")
        self.gridLayout_2.addWidget(self.edDistrict, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)
        self.comboProvince = QtGui.QComboBox(self.groupBox_2)
        self.comboProvince.setObjectName("comboProvince")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.gridLayout_2.addWidget(self.comboProvince, 2, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.edCity = QtGui.QLineEdit(self.groupBox_2)
        self.edCity.setObjectName("edCity")
        self.gridLayout_2.addWidget(self.edCity, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.edCEP = QtGui.QLineEdit(self.groupBox_2)
        self.edCEP.setObjectName("edCEP")
        self.gridLayout_2.addWidget(self.edCEP, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(331, 151))
        self.groupBox_3.setMaximumSize(QtCore.QSize(331, 151))
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet(" QGroupBox {\n"
"     font-weight: bold;\n"
"     border: 2px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 25px;\n"
" }\n"
"\n"
" QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top left;\n"
" }")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.edPhoneRes = QtGui.QLineEdit(self.groupBox_3)
        self.edPhoneRes.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.edPhoneRes.setPlaceholderText("")
        self.edPhoneRes.setObjectName("edPhoneRes")
        self.gridLayout_3.addWidget(self.edPhoneRes, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.edPhoneCom = QtGui.QLineEdit(self.groupBox_3)
        self.edPhoneCom.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.edPhoneCom.setPlaceholderText("")
        self.edPhoneCom.setObjectName("edPhoneCom")
        self.gridLayout_3.addWidget(self.edPhoneCom, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.edPhoneCell = QtGui.QLineEdit(self.groupBox_3)
        self.edPhoneCell.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.edPhoneCell.setPlaceholderText("")
        self.edPhoneCell.setObjectName("edPhoneCell")
        self.gridLayout_3.addWidget(self.edPhoneCell, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.page)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.buttonBox = QtGui.QDialogButtonBox(self.tab)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        Dock.setWidget(self.Contents)

        self.retranslateUi(Dock)
        self.tabWidget.setCurrentIndex(0)
        self.comboProvince.setCurrentIndex(24)
        QtCore.QMetaObject.connectSlotsByName(Dock)
        Dock.setTabOrder(self.edFullName, self.edNickname)
        Dock.setTabOrder(self.edNickname, self.edRG)
        Dock.setTabOrder(self.edRG, self.edCPF)
        Dock.setTabOrder(self.edCPF, self.comboBox)
        Dock.setTabOrder(self.comboBox, self.edProfession)
        Dock.setTabOrder(self.edProfession, self.edEmail)
        Dock.setTabOrder(self.edEmail, self.edStreet)
        Dock.setTabOrder(self.edStreet, self.edComplement)
        Dock.setTabOrder(self.edComplement, self.edDistrict)
        Dock.setTabOrder(self.edDistrict, self.comboProvince)
        Dock.setTabOrder(self.comboProvince, self.edCity)
        Dock.setTabOrder(self.edCity, self.edCEP)
        Dock.setTabOrder(self.edCEP, self.edPhoneRes)
        Dock.setTabOrder(self.edPhoneRes, self.edPhoneCom)
        Dock.setTabOrder(self.edPhoneCom, self.edPhoneCell)
        Dock.setTabOrder(self.edPhoneCell, self.buttonBox)
        Dock.setTabOrder(self.buttonBox, self.tabWidget)
        Dock.setTabOrder(self.tabWidget, self.scrollArea)

    def retranslateUi(self, Dock):
        Dock.setToolTip(QtGui.QApplication.translate("Dock", "Cadastro de Associados", None, QtGui.QApplication.UnicodeUTF8))
        Dock.setWindowTitle(QtGui.QApplication.translate("Dock", "Cadastro de Associados", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setToolTip(QtGui.QApplication.translate("Dock", "Dados Pessoais", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dock", "Dados Pessoais", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dock", "Solteiro(a)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Dock", "Casado(a)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Dock", "Divorciado(a)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Dock", "Viúvo(a)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dock", "CPF:", None, QtGui.QApplication.UnicodeUTF8))
        self.edCPF.setInputMask(QtGui.QApplication.translate("Dock", "999.999.999-99;_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dock", "Estado Civil:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dock", "Nome:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dock", "E-Mail:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dock", "RG:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dock", "Apelido:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dock", "Profissão:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setToolTip(QtGui.QApplication.translate("Dock", "Endereço", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dock", "Endereço", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dock", "Logradouro:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dock", "Complemento:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dock", "Bairro:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dock", "Estado:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(0, QtGui.QApplication.translate("Dock", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(1, QtGui.QApplication.translate("Dock", "AL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(2, QtGui.QApplication.translate("Dock", "AP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(3, QtGui.QApplication.translate("Dock", "AM", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(4, QtGui.QApplication.translate("Dock", "BA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(5, QtGui.QApplication.translate("Dock", "CE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(6, QtGui.QApplication.translate("Dock", "DF", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(7, QtGui.QApplication.translate("Dock", "ES", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(8, QtGui.QApplication.translate("Dock", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(9, QtGui.QApplication.translate("Dock", "MA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(10, QtGui.QApplication.translate("Dock", "MT", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(11, QtGui.QApplication.translate("Dock", "MS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(12, QtGui.QApplication.translate("Dock", "MG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(13, QtGui.QApplication.translate("Dock", "PA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(14, QtGui.QApplication.translate("Dock", "PB", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(15, QtGui.QApplication.translate("Dock", "PR", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(16, QtGui.QApplication.translate("Dock", "PE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(17, QtGui.QApplication.translate("Dock", "PI", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(18, QtGui.QApplication.translate("Dock", "RJ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(19, QtGui.QApplication.translate("Dock", "RN", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(20, QtGui.QApplication.translate("Dock", "RS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(21, QtGui.QApplication.translate("Dock", "RO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(22, QtGui.QApplication.translate("Dock", "RR", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(23, QtGui.QApplication.translate("Dock", "SC", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(24, QtGui.QApplication.translate("Dock", "SP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(25, QtGui.QApplication.translate("Dock", "SE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboProvince.setItemText(26, QtGui.QApplication.translate("Dock", "TO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dock", "Cidade:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dock", "CEP:", None, QtGui.QApplication.UnicodeUTF8))
        self.edCEP.setInputMask(QtGui.QApplication.translate("Dock", "99.999-999;_", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setToolTip(QtGui.QApplication.translate("Dock", "Telefones", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dock", "Telefones", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dock", "Residencial:", None, QtGui.QApplication.UnicodeUTF8))
        self.edPhoneRes.setToolTip(QtGui.QApplication.translate("Dock", "DDD + Número", None, QtGui.QApplication.UnicodeUTF8))
        self.edPhoneRes.setInputMask(QtGui.QApplication.translate("Dock", "(DD)9999-9999;_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dock", "Comercial:", None, QtGui.QApplication.UnicodeUTF8))
        self.edPhoneCom.setToolTip(QtGui.QApplication.translate("Dock", "DDD + Número", None, QtGui.QApplication.UnicodeUTF8))
        self.edPhoneCom.setInputMask(QtGui.QApplication.translate("Dock", "(DD)9999-9999;_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dock", "Celular:", None, QtGui.QApplication.UnicodeUTF8))
        self.edPhoneCell.setToolTip(QtGui.QApplication.translate("Dock", "DDD + Número", None, QtGui.QApplication.UnicodeUTF8))
        self.edPhoneCell.setInputMask(QtGui.QApplication.translate("Dock", "(DD)99999-9999;_", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dock", "Novo Cadastro", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dock", "Buscar", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
