# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/lib/ui/add_activity.ui'
#
# Created: Tue Feb 25 15:07:51 2014
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dock(object):
    def setupUi(self, Dock):
        Dock.setObjectName("Dock")
        Dock.setWindowModality(QtCore.Qt.WindowModal)
        Dock.resize(774, 445)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dock.sizePolicy().hasHeightForWidth())
        Dock.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/activity_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dock.setWindowIcon(icon)
        Dock.setStyleSheet("QDockWidget::title\n"
"{\n"
"   font-family: \"Roboto Lt\";\n"
"   font-size: 18pt;\n"
"   background: lightgray;\n"
"   padding-left: 10px; \n"
"   padding-top: 4px;\n"
"}")
        Dock.setFloating(False)
        Dock.setFeatures(QtGui.QDockWidget.DockWidgetClosable)
        Dock.setAllowedAreas(QtCore.Qt.TopDockWidgetArea)
        self.Contents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Contents.sizePolicy().hasHeightForWidth())
        self.Contents.setSizePolicy(sizePolicy)
        self.Contents.setObjectName("Contents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.Contents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabRegister = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabRegister.sizePolicy().hasHeightForWidth())
        self.tabRegister.setSizePolicy(sizePolicy)
        self.tabRegister.setObjectName("tabRegister")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabRegister)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtGui.QScrollArea(self.tabRegister)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 730, 265))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(703, 247))
        self.groupBox.setMaximumSize(QtCore.QSize(703, 231))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(" QGroupBox {\n"
"     font-weight: bold;\n"
"     border: 2px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 25px;\n"
" }\n"
"\n"
" QGroupBox::title {\n"
"     background-color: transparent;\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top left;\n"
" }")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboDescription = QtGui.QComboBox(self.groupBox)
        self.comboDescription.setEditable(False)
        self.comboDescription.setObjectName("comboDescription")
        self.comboDescription.addItem("")
        self.comboDescription.addItem("")
        self.comboDescription.addItem("")
        self.comboDescription.addItem("")
        self.comboDescription.addItem("")
        self.comboDescription.addItem("")
        self.gridLayout.addWidget(self.comboDescription, 0, 1, 1, 4)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.comboWeekday = QtGui.QComboBox(self.groupBox)
        self.comboWeekday.setObjectName("comboWeekday")
        self.comboWeekday.addItem("")
        self.comboWeekday.addItem("")
        self.comboWeekday.addItem("")
        self.comboWeekday.addItem("")
        self.comboWeekday.addItem("")
        self.comboWeekday.addItem("")
        self.comboWeekday.addItem("")
        self.gridLayout.addWidget(self.comboWeekday, 1, 3, 1, 2)
        self.comboRoom = QtGui.QComboBox(self.groupBox)
        self.comboRoom.setObjectName("comboRoom")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.comboRoom.addItem("")
        self.gridLayout.addWidget(self.comboRoom, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.editTime = QtGui.QTimeEdit(self.groupBox)
        self.editTime.setTime(QtCore.QTime(19, 0, 0))
        self.editTime.setObjectName("editTime")
        self.gridLayout.addWidget(self.editTime, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.page)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabRegister)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tabRegister, icon, "")
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName("tabSearch")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSearch)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSearch, icon1, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        Dock.setWidget(self.Contents)

        self.retranslateUi(Dock)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dock)
        Dock.setTabOrder(self.comboDescription, self.comboRoom)
        Dock.setTabOrder(self.comboRoom, self.comboWeekday)
        Dock.setTabOrder(self.comboWeekday, self.editTime)
        Dock.setTabOrder(self.editTime, self.buttonBox)
        Dock.setTabOrder(self.buttonBox, self.tabWidget)
        Dock.setTabOrder(self.tabWidget, self.scrollArea)

    def retranslateUi(self, Dock):
        Dock.setToolTip(QtGui.QApplication.translate("Dock", "Cadastro de Atividades", None, QtGui.QApplication.UnicodeUTF8))
        Dock.setWindowTitle(QtGui.QApplication.translate("Dock", "Cadastro de Atividades", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setToolTip(QtGui.QApplication.translate("Dock", "Dados Pessoais", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dock", "Atividade", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDescription.setItemText(0, QtGui.QApplication.translate("Dock", "Atendimento Fraterno", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDescription.setItemText(1, QtGui.QApplication.translate("Dock", "Reunião Pública", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDescription.setItemText(2, QtGui.QApplication.translate("Dock", "Reunião de Estudos", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDescription.setItemText(3, QtGui.QApplication.translate("Dock", "Reunião Mediúnica", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDescription.setItemText(4, QtGui.QApplication.translate("Dock", "Desobsessão", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDescription.setItemText(5, QtGui.QApplication.translate("Dock", "Voluntariado", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dock", "Descrição:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dock", "Sala:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dock", "Dia da Semana:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboWeekday.setItemText(0, QtGui.QApplication.translate("Dock", "Segunda-Feira", None, QtGui.QApplication.UnicodeUTF8))
        self.comboWeekday.setItemText(1, QtGui.QApplication.translate("Dock", "Terça-Feira", None, QtGui.QApplication.UnicodeUTF8))
        self.comboWeekday.setItemText(2, QtGui.QApplication.translate("Dock", "Quarta-Feira", None, QtGui.QApplication.UnicodeUTF8))
        self.comboWeekday.setItemText(3, QtGui.QApplication.translate("Dock", "Quinta-Feira", None, QtGui.QApplication.UnicodeUTF8))
        self.comboWeekday.setItemText(4, QtGui.QApplication.translate("Dock", "Sexta-Feira", None, QtGui.QApplication.UnicodeUTF8))
        self.comboWeekday.setItemText(5, QtGui.QApplication.translate("Dock", "Sábado", None, QtGui.QApplication.UnicodeUTF8))
        self.comboWeekday.setItemText(6, QtGui.QApplication.translate("Dock", "Domingo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(0, QtGui.QApplication.translate("Dock", "Nenhuma", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(1, QtGui.QApplication.translate("Dock", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(2, QtGui.QApplication.translate("Dock", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(3, QtGui.QApplication.translate("Dock", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(4, QtGui.QApplication.translate("Dock", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(5, QtGui.QApplication.translate("Dock", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(6, QtGui.QApplication.translate("Dock", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(7, QtGui.QApplication.translate("Dock", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(8, QtGui.QApplication.translate("Dock", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(9, QtGui.QApplication.translate("Dock", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(10, QtGui.QApplication.translate("Dock", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(11, QtGui.QApplication.translate("Dock", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboRoom.setItemText(12, QtGui.QApplication.translate("Dock", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dock", "Horário:", None, QtGui.QApplication.UnicodeUTF8))
        self.editTime.setDisplayFormat(QtGui.QApplication.translate("Dock", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegister), QtGui.QApplication.translate("Dock", "Novo Cadastro", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), QtGui.QApplication.translate("Dock", "Buscar", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
