# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/lib/ui/main.ui'
#
# Created: Tue Feb  4 10:27:02 2014
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRegisters = QtGui.QMenu(self.menubar)
        self.menuRegisters.setObjectName("menuRegisters")
        self.menuSales = QtGui.QMenu(self.menubar)
        self.menuSales.setObjectName("menuSales")
        self.menuReports = QtGui.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuLibrary = QtGui.QMenu(self.menubar)
        self.menuLibrary.setObjectName("menuLibrary")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.NoToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRegAssociate = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/associate_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegAssociate.setIcon(icon3)
        self.actionRegAssociate.setIconVisibleInMenu(True)
        self.actionRegAssociate.setObjectName("actionRegAssociate")
        self.actionSellBooks = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSellBooks.setIcon(icon4)
        self.actionSellBooks.setIconVisibleInMenu(True)
        self.actionSellBooks.setObjectName("actionSellBooks")
        self.actionSellProduct = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSellProduct.setIcon(icon5)
        self.actionSellProduct.setIconVisibleInMenu(True)
        self.actionSellProduct.setObjectName("actionSellProduct")
        self.actionSellEvents = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/events.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSellEvents.setIcon(icon6)
        self.actionSellEvents.setIconVisibleInMenu(True)
        self.actionSellEvents.setObjectName("actionSellEvents")
        self.actionRegBook = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/book_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegBook.setIcon(icon7)
        self.actionRegBook.setIconVisibleInMenu(True)
        self.actionRegBook.setObjectName("actionRegBook")
        self.actionRegProduct = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/product_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegProduct.setIcon(icon8)
        self.actionRegProduct.setIconVisibleInMenu(True)
        self.actionRegProduct.setObjectName("actionRegProduct")
        self.actionLibLend = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/book_lend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLibLend.setIcon(icon9)
        self.actionLibLend.setIconVisibleInMenu(True)
        self.actionLibLend.setObjectName("actionLibLend")
        self.actionLibReturn = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/book_return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLibReturn.setIcon(icon10)
        self.actionLibReturn.setIconVisibleInMenu(True)
        self.actionLibReturn.setObjectName("actionLibReturn")
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/preferences.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon11)
        self.actionPreferences.setIconVisibleInMenu(True)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon12)
        self.actionCopy.setIconVisibleInMenu(True)
        self.actionCopy.setObjectName("actionCopy")
        self.actionRepSales = QtGui.QAction(MainWindow)
        self.actionRepSales.setObjectName("actionRepSales")
        self.actionRepLibrary = QtGui.QAction(MainWindow)
        self.actionRepLibrary.setObjectName("actionRepLibrary")
        self.actionRepBazar = QtGui.QAction(MainWindow)
        self.actionRepBazar.setObjectName("actionRepBazar")
        self.actionLivros = QtGui.QAction(MainWindow)
        self.actionLivros.setObjectName("actionLivros")
        self.actionSearch = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch.setIcon(icon13)
        self.actionSearch.setObjectName("actionSearch")
        self.actionPendencies = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/pending.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPendencies.setIcon(icon14)
        self.actionPendencies.setObjectName("actionPendencies")
        self.menuFile.addAction(self.actionExit)
        self.menuRegisters.addAction(self.actionRegAssociate)
        self.menuRegisters.addAction(self.actionRegBook)
        self.menuRegisters.addAction(self.actionRegProduct)
        self.menuSales.addAction(self.actionSellBooks)
        self.menuSales.addAction(self.actionSellProduct)
        self.menuSales.addAction(self.actionSellEvents)
        self.menuReports.addAction(self.actionRepSales)
        self.menuReports.addAction(self.actionLivros)
        self.menuReports.addAction(self.actionRepBazar)
        self.menuReports.addAction(self.actionRepLibrary)
        self.menuHelp.addAction(self.actionAbout)
        self.menuLibrary.addAction(self.actionLibLend)
        self.menuLibrary.addAction(self.actionLibReturn)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRegisters.menuAction())
        self.menubar.addAction(self.menuSales.menuAction())
        self.menubar.addAction(self.menuLibrary.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionSellBooks)
        self.toolBar.addAction(self.actionSellProduct)
        self.toolBar.addAction(self.actionSellEvents)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSearch)
        self.toolBar.addAction(self.actionPendencies)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Seareiros", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&Arquivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRegisters.setTitle(QtGui.QApplication.translate("MainWindow", "&Cadastros", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSales.setTitle(QtGui.QApplication.translate("MainWindow", "&Vendas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuReports.setTitle(QtGui.QApplication.translate("MainWindow", "&Relatórios", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLibrary.setTitle(QtGui.QApplication.translate("MainWindow", "&Biblioteca", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "Sobre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegAssociate.setText(QtGui.QApplication.translate("MainWindow", "Associado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSellBooks.setText(QtGui.QApplication.translate("MainWindow", "Livros", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSellProduct.setText(QtGui.QApplication.translate("MainWindow", "Bazar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSellEvents.setText(QtGui.QApplication.translate("MainWindow", "Eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegBook.setText(QtGui.QApplication.translate("MainWindow", "Livro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegProduct.setText(QtGui.QApplication.translate("MainWindow", "Produto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLibLend.setText(QtGui.QApplication.translate("MainWindow", "Alugar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLibReturn.setText(QtGui.QApplication.translate("MainWindow", "Devolver", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferências", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copiar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRepSales.setText(QtGui.QApplication.translate("MainWindow", "Vendas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRepLibrary.setText(QtGui.QApplication.translate("MainWindow", "Biblioteca", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRepBazar.setText(QtGui.QApplication.translate("MainWindow", "Bazar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLivros.setText(QtGui.QApplication.translate("MainWindow", "Livros", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch.setText(QtGui.QApplication.translate("MainWindow", "Pesquisar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch.setToolTip(QtGui.QApplication.translate("MainWindow", "Pesquisar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPendencies.setText(QtGui.QApplication.translate("MainWindow", "Pendências", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPendencies.setToolTip(QtGui.QApplication.translate("MainWindow", "Pendências", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
